import { theme } from '../theme';

interface SariSariStoreProps {
  onBack: () => void;
}

export function SariSariStore({ onBack }: SariSariStoreProps) {
  return (
    <div style={{
      position: 'absolute',
      inset: 0,
      backgroundColor: theme.colors.background,
      display: 'flex',
      flexDirection: 'column',
      padding: '40px',
      color: theme.colors.textPrimary
    }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '40px' }}>
        <div>
          <button onClick={onBack} style={{
            background: 'none',
            border: 'none',
            color: theme.colors.textSecondary,
            cursor: 'pointer',
            fontSize: '16px',
            marginBottom: '10px',
            padding: 0,
            textDecoration: 'underline'
          }}>
            ← Back to Menu
          </button>
          <h1 style={{ margin: 0, fontSize: '32px', textTransform: 'uppercase', color: theme.colors.accent }}>Sari-Sari Store</h1>
          <div style={{ color: theme.colors.textMuted }}>Meta-Progression Upgrades</div>
        </div>
        <div style={{ display: 'flex', alignItems: 'center', gap: '10px', backgroundColor: theme.colors.surface, padding: '10px 20px', borderRadius: '20px', border: `2px solid ${theme.colors.gold}` }}>
          <span style={{ fontWeight: 'bold', fontSize: '20px', color: theme.colors.gold }}>1,250</span>
          <span style={{ textTransform: 'uppercase', fontSize: '14px' }}>Hope</span>
        </div>
      </div>

      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(280px, 1fr))', gap: '20px' }}>
        {[
          { title: '3x Eden Cards', desc: 'Cards used to upgrade Eden.', cost: 300, level: 'Cards' },
          { title: '1x Teacher Card', desc: 'Card used to upgrade Teacher.', cost: 150, level: 'Cards' },
          { title: 'Megaphone Upgrade', desc: 'Increases base Voices generated by 10%.', cost: 500, level: '2 / 5' },
          { title: 'Tougher Barricades', desc: 'Heroes gain +50 max HP.', cost: 800, level: '1 / 3' },
          { title: 'Bayanihan Spirit', desc: 'Bayanihan Act charges 5% faster.', cost: 1200, level: '0 / 5' }
        ].map((item, i) => (
          <div key={i} style={{
            backgroundColor: theme.colors.surface,
            border: `2px solid ${theme.colors.border}`,
            borderRadius: '12px',
            padding: '20px',
            display: 'flex',
            flexDirection: 'column',
            justifyContent: 'space-between'
          }}>
            <div>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: '10px' }}>
                <h3 style={{ margin: 0, fontSize: '18px', color: theme.colors.accent }}>{item.title}</h3>
                <span style={{ fontSize: '12px', color: theme.colors.textMuted, backgroundColor: theme.colors.background, padding: '2px 6px', borderRadius: '4px' }}>Lvl {item.level}</span>
              </div>
              <p style={{ fontSize: '14px', color: theme.colors.textMuted, lineHeight: '1.4', marginBottom: '20px' }}>{item.desc}</p>
            </div>
            <button style={{
              backgroundColor: theme.colors.gold,
              color: '#000',
              border: 'none',
              padding: '10px',
              borderRadius: '6px',
              fontWeight: 'bold',
              cursor: 'pointer',
              display: 'flex',
              justifyContent: 'center',
              alignItems: 'center',
              gap: '5px',
              textTransform: 'uppercase'
            }}>
              Buy - {item.cost} Hope
            </button>
          </div>
        ))}
      </div>
      
      <button style={{
        marginTop: 'auto',
        alignSelf: 'flex-start',
        padding: '12px 24px',
        backgroundColor: 'transparent',
        color: theme.colors.textMuted,
        border: `2px solid ${theme.colors.border}`,
        borderRadius: '8px',
        cursor: 'pointer',
        textTransform: 'uppercase',
        fontWeight: 'bold',
        transition: 'all 0.2s'
      }}>
        Back to Campaign
      </button>
    </div>
  );
}
